/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.lang.Integer;
import java.awt.Dimension;
import java.awt.Toolkit;



/**
 *
 * @author Toshiba
 */
public class FormPerpustakaan extends javax.swing.JFrame {
    Perpustakaan perpus = new Perpustakaan();
    

    /**
     * Creates new form FormPerpustakaan
     */
    public FormPerpustakaan() {
        initComponents();
        setTitle("Aplikasi Perpustakaan");
        cbgenre.addItem("PILIH");
        cbgenre.addItem("Fantasi");
        cbgenre.addItem("Aksi");
        cbgenre.addItem("Edukasi");
        cbgenre.addItem("Romansa");
        cbjudul.addItem("");
        
//        SpinnerModel model = new SpinnerNumberModel(0, 1, 60, 1);
//        spinnerModel.setMinimum(0);
//        spinnerModel.setMaximum(60);
        
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        getContentPane().setBackground(Color.BLUE);
        
        
}
    void nonaktif(){
        tidMember.setEnabled(false);
        tusername.setEnabled(false);
        cbgenre.setEnabled(false);
        cbjudul.setEnabled(false);
        tpenulis.setEnabled(false);
        tpenerbit.setEnabled(false);
        dcwaktu_peminjaman.setEnabled(false);
        sdurasiPeminjaman.setEnabled(false);
        twaktu_pengembalian.setEnabled(false);
        bhitunghari.setEnabled(false);
        tsubtotal.setEnabled(false);
        bpinjam.setEnabled(false);
        bselesai.setEnabled(false);
    }
    
   
    void bersih(){
        tidMember.setText("");
        tusername.setText("");
        cbgenre.setSelectedIndex(0);
        cbjudul.setSelectedIndex(0);
        tkodeBuku.setText("");
        tpenulis.setText("");
        tpenerbit.setText("");
        dcwaktu_peminjaman.setDate(null);
        
        Object initialValue = 1;
        sdurasiPeminjaman.setValue(initialValue);
        twaktu_pengembalian.setText("");
        tsubtotal.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tidMember = new javax.swing.JTextField();
        tusername = new javax.swing.JTextField();
        cbgenre = new javax.swing.JComboBox();
        cbjudul = new javax.swing.JComboBox();
        tpenulis = new javax.swing.JTextField();
        tpenerbit = new javax.swing.JTextField();
        dcwaktu_peminjaman = new com.toedter.calendar.JDateChooser();
        sdurasiPeminjaman = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        twaktu_pengembalian = new javax.swing.JTextField();
        bhitunghari = new javax.swing.JButton();
        tsubtotal = new javax.swing.JTextField();
        bpinjam = new javax.swing.JButton();
        bselesai = new javax.swing.JButton();
        bmulai = new javax.swing.JButton();
        tkodeBuku = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btambah = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ttotalHarga = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        totalPembayaran = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan");
        setBackground(new java.awt.Color(0, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1366, 703));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(819, 650));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peminjaman Buku");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(312, 51, 190, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aplikasi Perpustakaan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 16, 230, 29);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setText("Nama Peminjam");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 204, 255));
        jLabel13.setText("ID Member");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Kategori Buku");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Judul Buku");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("Penulis Buku");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 255));
        jLabel8.setText("Penerbit Buku");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("Waktu Peminjaman");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 255));
        jLabel9.setText("Durasi Peminjaman");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 255));
        jLabel11.setText("Waktu Pengembalian");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 255));
        jLabel12.setText("Sub Harga");

        tidMember.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tidMember.setForeground(new java.awt.Color(51, 51, 51));
        tidMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidMemberActionPerformed(evt);
            }
        });

        tusername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusernameActionPerformed(evt);
            }
        });

        cbgenre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbgenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgenreActionPerformed(evt);
            }
        });

        cbjudul.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbjudul.setMinimumSize(new java.awt.Dimension(38, 27));
        cbjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjudulActionPerformed(evt);
            }
        });

        tpenulis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tpenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpenulisActionPerformed(evt);
            }
        });

        tpenerbit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpenerbitActionPerformed(evt);
            }
        });

        dcwaktu_peminjaman.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dcwaktu_peminjaman.setDateFormatString("dd MMM yyyy");
        dcwaktu_peminjaman.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        sdurasiPeminjaman.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sdurasiPeminjaman.setModel(new javax.swing.SpinnerNumberModel(1, 1, 60, 1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 255));
        jLabel10.setText("Hari");

        twaktu_pengembalian.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        twaktu_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twaktu_pengembalianActionPerformed(evt);
            }
        });

        bhitunghari.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bhitunghari.setText("HITUNG HARI");
        bhitunghari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitunghariActionPerformed(evt);
            }
        });

        tsubtotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsubtotalActionPerformed(evt);
            }
        });

        bpinjam.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bpinjam.setText("PINJAM");
        bpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpinjamActionPerformed(evt);
            }
        });

        bselesai.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bselesai.setText("SELESAI");
        bselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bselesaiActionPerformed(evt);
            }
        });

        bmulai.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bmulai.setText("MULAI");
        bmulai.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bmulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulaiActionPerformed(evt);
            }
        });

        tkodeBuku.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tkodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkodeBukuActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 255));
        jLabel14.setText("Kode Buku");

        btambah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btambah.setText("TAMBAH");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 255));
        jLabel15.setText("Total Harga");

        ttotalHarga.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ttotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotalHargaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 204, 255));
        jLabel16.setText("Total Pembayaran");

        totalPembayaran.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(tidMember, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbgenre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sdurasiPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addComponent(tkodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bhitunghari))))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(dcwaktu_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cbjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(twaktu_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bmulai)
                        .addGap(18, 18, 18)
                        .addComponent(btambah)
                        .addGap(18, 18, 18)
                        .addComponent(bpinjam)
                        .addGap(18, 18, 18)
                        .addComponent(bselesai)
                        .addGap(95, 95, 95))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel4, jLabel8, jLabel9});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel3, jLabel5, jLabel6, jLabel7});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tidMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cbjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbgenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tkodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(dcwaktu_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdurasiPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(twaktu_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bhitunghari)
                    .addComponent(tsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bmulai)
                        .addComponent(bpinjam)
                        .addComponent(bselesai)
                        .addComponent(btambah)
                        .addComponent(jLabel16)
                        .addComponent(totalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(ttotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)))
                .addGap(71, 71, 71))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel3, jLabel5, jLabel6, jLabel7});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel4, jLabel8, jLabel9});

        jPanel1.add(jPanel2);
        jPanel2.setBounds(24, 98, 870, 540);

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textArea.setForeground(new java.awt.Color(0, 51, 255));
        textArea.setRows(5);
        textArea.setPreferredSize(new java.awt.Dimension(170, 104));
        jScrollPane1.setViewportView(textArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(910, 100, 410, 540);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 1346, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulaiActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_bmulaiActionPerformed

    private void bselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bselesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bselesaiActionPerformed

    private void bpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpinjamActionPerformed

    private void tsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsubtotalActionPerformed

    private void bhitunghariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitunghariActionPerformed
        // TODO add your handling code here:
        Date waktuPeminjaman = dcwaktu_peminjaman.getDate();
        int durasiPeminjaman = (int) sdurasiPeminjaman.getValue();

        //        int durasi = Integer.parseInt(durasiPeminjaman);

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(waktuPeminjaman);
        calendar.add(Calendar.DAY_OF_MONTH, durasiPeminjaman);

        Date tanggalHasil = calendar.getTime();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMM yyyy");
        String tanggalHasilStr = dateFormat.format(tanggalHasil);

        twaktu_pengembalian.setText(tanggalHasilStr);
    }//GEN-LAST:event_bhitunghariActionPerformed

    private void twaktu_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twaktu_pengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twaktu_pengembalianActionPerformed

    private void tpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpenerbitActionPerformed

    private void tpenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpenulisActionPerformed

    private void cbjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjudulActionPerformed
        // TODO add your handling code here:
        String judulBuku = cbjudul.getSelectedItem().toString();
        String[] dataBuku = perpus.getDataBuku(judulBuku);
        tpenulis.setText(dataBuku[0]);
        tpenerbit.setText(dataBuku[1]);
        tkodeBuku.setText(dataBuku[2]);
    }//GEN-LAST:event_cbjudulActionPerformed

    private void cbgenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgenreActionPerformed
        // TODO add your handling code here:
        if(cbgenre.getSelectedItem().equals("PILIH")){
            //            cbjudul.setModel("PILIH");
            tpenulis.setText("");
            tpenerbit.setText("");
        }
        else if(cbgenre.getSelectedItem().equals("Fantasi")){
            String[] judulBukuFantasi = perpus.getJudulBuku("Fantasi");
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(judulBukuFantasi);
            cbjudul.setModel(model);

        }
        else if(cbgenre.getSelectedItem().equals("Aksi")){
            String[] judulBukuAksi = perpus.getJudulBuku("Aksi");
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(judulBukuAksi);
            cbjudul.setModel(model);
        }
        else if(cbgenre.getSelectedItem().equals("Edukasi")){
            String[] judulBukuEdukasi = perpus.getJudulBuku("Edukasi");
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(judulBukuEdukasi);
            cbjudul.setModel(model);
        }
        else if(cbgenre.getSelectedItem().equals("Romansa")){
            String[] judulBukuRomansa = perpus.getJudulBuku("Romansa");
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(judulBukuRomansa);
            cbjudul.setModel(model);
        }
    }//GEN-LAST:event_cbgenreActionPerformed

    private void tusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusernameActionPerformed
        // TODO add your handling code here:
        cbgenre.requestFocus();
    }//GEN-LAST:event_tusernameActionPerformed

    private void tidMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidMemberActionPerformed
        // TODO add your handling code here:
        tusername.requestFocus();
    }//GEN-LAST:event_tidMemberActionPerformed

    private void tkodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkodeBukuActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        // TODO add your handling code here:
        String idMember = tidMember.getText();
        String username = tusername.getText();
        String genreBuku = (String) cbgenre.getSelectedItem();
        String judulBuku = (String) cbjudul.getSelectedItem();
        String [] dataBuku = perpus.getDataBuku(judulBuku);
        String penulisBuku = dataBuku[0];
        String penerbitBuku = dataBuku[1];
        String kodeBuku = dataBuku[2];
        Date waktuPeminjaman = dcwaktu_peminjaman.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMM yyyy");
        String tanggalWaktuStr = dateFormat.format(waktuPeminjaman);
        
        
        
        
        String dataPeminjaman = "ID Member: " + idMember + "\n"
                + "Nama Peminjam: " + username + "\n"
                + "Kategori Buku: " + genreBuku + "\n"
                + "Judul Buku: " + judulBuku + "\n"
                + "Kode Buku: " + kodeBuku + "\n"
                + "Penulis Buku: " + penulisBuku + "\n"
                + "Penerbit Buku: " + penerbitBuku + "\n"
                + "Waktu Peminjaman: " + tanggalWaktuStr + "\n\n";
        
        textArea.append(dataPeminjaman);
        
        bersih();
//        tidMember.setText("");
//        tusername.setText("");
//        cbgenre.setSelectedItem("PILIH");
//        cbjudul.setSelectedItem("");
//        tkodeBuku.setText("");
//        tpenulis.setText("");
//        tpenerbit.setText("");
        
        
    }//GEN-LAST:event_btambahActionPerformed

    private void ttotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttotalHargaActionPerformed

    private void totalPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPerpustakaan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhitunghari;
    private javax.swing.JButton bmulai;
    private javax.swing.JButton bpinjam;
    private javax.swing.JButton bselesai;
    private javax.swing.JButton btambah;
    private javax.swing.JComboBox cbgenre;
    private javax.swing.JComboBox cbjudul;
    private com.toedter.calendar.JDateChooser dcwaktu_peminjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sdurasiPeminjaman;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField tidMember;
    private javax.swing.JTextField tkodeBuku;
    private javax.swing.JTextField totalPembayaran;
    private javax.swing.JTextField tpenerbit;
    private javax.swing.JTextField tpenulis;
    private javax.swing.JTextField tsubtotal;
    private javax.swing.JTextField ttotalHarga;
    private javax.swing.JTextField tusername;
    private javax.swing.JTextField twaktu_pengembalian;
    // End of variables declaration//GEN-END:variables
}
